//7. Program to store store top 50 artist in India and print it

class Artist{
	public static void main(String[] args){
		String artist="1.Arjit Singh";
		System.out.println(artist);
		artist="2.Shreya Ghoshal";
		System.out.println(artist);
		artist="3.Pritam";
		System.out.println(artist);
		artist="4.Diljit Dosanjh";
		System.out.println(artist);
		artist="5.A.R.Rahman";
		System.out.println(artist);
		artist="6.Anirudh Ravichander";
		System.out.println(artist);
		artist="7.Yo Yo Honey Singh ";
		System.out.println(artist);
		artist="8.Badshah";
		System.out.println(artist);
		artist="9.Vishal Mishra";
		System.out.println(artist);
		artist="10.Neha Kakkar";
		System.out.println(artist);
		artist="11.Sonu Nigam";
		System.out.println(artist);
		artist="12.Alka Yagnik";
		System.out.println(artist);
		artist="13.Udit Narayan";
		System.out.println(artist);
		artist="14.Sunidhi Chauhan";
		System.out.println(artist);
		artist="15.Jubin Nautiyal";
		System.out.println(artist);
		artist="16.Atif Aslam";
		System.out.println(artist);
		artist="17.Shankar-Ehsaan-Loy";
		System.out.println(artist);
		artist="18.Tanishk Bagchi";
		System.out.println(artist);
		artist="19.Mithoon";
		System.out.println(artist);
		artist="20.Armaan Malik";
		System.out.println(artist);
		artist="21.Amit Trivedi";
		System.out.println(artist);
		artist="22.Sachet-Parampara";
		System.out.println(artist);
		artist="23.Mohit Chauhan";
		System.out.println(artist);
		artist="24.Shilpa Rao";
		System.out.println(artist);
		artist="25.Joita Gandhi";
		System.out.println(artist);
		artist="26.Sidhu Moose Wala";
		System.out.println(artist);
		artist="27.Karan Aujla";
		System.out.println(artist);
		artist="28.AP Dhillon";
		System.out.println(artist);
		artist="29.King";
		System.out.println(artist);
		artist="30.Divine";
		System.out.println(artist);
		artist="31.Shubh";
		System.out.println(artist);
		artist="32.Hanumankind";
		System.out.println(artist);
		artist="33.B Praak";
		System.out.println(artist);
		artist="34.Jasmine Sandlas";
		System.out.println(artist);
		artist="35.Sid Sriram";
		System.out.println(artist);
		artist="36.Emiway Bantai";
		System.out.println(artist);
		artist="37.Talwiinder";
		System.out.println(artist);
		artist="38.Guru Randhawa";
		System.out.println(artist);
		artist="39.Dhanda Nyoliwala";
		System.out.println(artist);
		artist="40.Krsna";
		System.out.println(artist);
		artist="41.Anuv Jain";
		System.out.println(artist);
		artist="42.Aditya Rikhari";
		System.out.println(artist);
		artist="43.Faheem Kuhad";
		System.out.println(artist);
		artist="44.Prateek Kuhad";
		System.out.println(artist);
		artist="45.Osho Jain";
		System.out.println(artist);
		artist="46.Reble";
		System.out.println(artist);
		artist="47.The Local Train";
		System.out.println(artist);
		artist="48.BloodyWood";
		System.out.println(artist);
		artist="49.Kushagra";
		System.out.println(artist);
		artist="50.Sanju Rathod";
		System.out.println(artist);
	}
}