//9. types on Dance in India

class Dance{
	public static void main(String[] args){
		String dance="1.Bharatanatyam";
		System.out.println(dance);
		dance="2.Kathak";
		System.out.println(dance);
		dance="3.Kathakali";
		System.out.println(dance);
		dance="4.Kuchipudi";
		System.out.println(dance);
		dance="5.Odissi";
		System.out.println(dance);
		dance="6.Manipuri";
		System.out.println(dance);
		dance="7.Mohiniyattam";
		System.out.println(dance);
		dance="8.Sattriya";
		System.out.println(dance);
		dance="9.Bhangra";
		System.out.println(dance);
		dance="10.Giddha";
		System.out.println(dance);
		dance="11.Jhumar";
		System.out.println(dance);
		dance="12.Chholiya";
		System.out.println(dance);
		dance="13.Garba";
		System.out.println(dance);
		dance="14.Dandiya Raas";
		System.out.println(dance);
		dance="15.Ghoomar";
		System.out.println(dance);
		dance="16.Kalbelia";
		System.out.println(dance);
		dance="17.Bhavai";
		System.out.println(dance);
		dance="18.Lavani";
		System.out.println(dance);
		dance="19.Bihu";
		System.out.println(dance);
		dance="20.chhau";
		System.out.println(dance);
		dance="21.Gotipua";
		System.out.println(dance);
		dance="22.Sambalpuri";
		System.out.println(dance);
		dance="23.Yakshagana";
		System.out.println(dance);
		dance="24.Dollu Kunitha";
		System.out.println(dance);
		dance="25.Kummi";
		System.out.println(dance);
		dance="26.Kolattam";
		System.out.println(dance);
		dance="27.Koragattam";
		System.out.println(dance);
		dance="28.Theyyam";
		System.out.println(dance);
		dance="29.Thirayattam";
		System.out.println(dance);
		dance="30.Santhali Dance";
		System.out.println(dance);
		dance="31.Gaur Dance";
		System.out.println(dance);
		dance="32.Karma Dance";
		System.out.println(dance);
		dance="33.Hojagiri";
		System.out.println(dance);
		dance="34.heraw";
		System.out.println(dance);
		dance="35.Bison Horn Dance";
		System.out.println(dance);
		dance="36.Wangala Dance";
		System.out.println(dance);
		dance="37.Rouf";
		System.out.println(dance);
		dance="38.Perini Shivantandavam";
		System.out.println(dance);
		dance="39.Dalkhai";
		System.out.println(dance);
		dance="40.Veeragase";
		System.out.println(dance);
		dance="41.Singhi Chham";
		System.out.println(dance);
		dance="42.Mask Dance";
		System.out.println(dance);
	}
}